package Definations;

import org.junit.runner.RunWith;
import io.cucumber.junit.CucumberOptions;
import io.cucumber.junit.Cucumber;

@RunWith(Cucumber.class)
@CucumberOptions(features="src/test/resources/Features",glue= {"Definations"}, 

		monochrome=true,

//Create a reports using PLUGIN tag
		plugin = {
				  
				  "pretty","html:target/HtmlReports/index.html"
						  ,"json:target/JsonRepost/report.json"
						  ,"junit:target/JunitReport/report.xml"
						  
					} 

/**variable "PLUGIN" then two key-values "pretty" and 
 * "html:target/HtmlReports/index.html"
 * "key:folder/New_Folder_Name/type of file
 * HTML reports generated by the PLUGIN will be saved 
 * in the target/HtmlReports/ directory, specifically in the index.html file.
**/

)

public class TestRunner {

}
